source 'https://rubygems.org'

gem 'angelo', github: 'kenichi/angelo'
gem 'celluloid-redis'
gem 'pg'
gem 'redis'
gem 'reel', github: 'celluloid/reel'
gem 'sequel'
gem 'terraformer'

group :dev do
  gem 'awesome_print'
  gem 'httpclient'
  gem 'pry'
  gem 'pry-nav'
end
