source 'https://rubygems.org'

gem 'angelo', '0.4.1'
gem 'celluloid-redis'
gem 'pg'
gem 'redis'
gem 'reel', '0.5.0'
gem 'sequel'
gem 'terraformer'

group :dev do
  gem 'awesome_print'
  gem 'httpclient'
  gem 'pry'
  gem 'pry-nav'
end
